// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeslaRent_01.WebApplication.Server.Data;

#nullable disable

namespace TeslaRent_01.WebApplication.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250511182830_AddCarInfoAndPhoneNumber")]
    partial class AddCarInfoAndPhoneNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeslaRent_01.WebApplication.Server.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<int>("DaysInService")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 4,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 5,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 6,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 7,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 8,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 9,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 10,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 11,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 12,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 13,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 14,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 15,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 16,
                            CarModelId = 1,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 17,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 18,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 19,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 20,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 21,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 22,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 23,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 24,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 25,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 26,
                            CarModelId = 2,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 27,
                            CarModelId = 3,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 28,
                            CarModelId = 3,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 29,
                            CarModelId = 3,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 30,
                            CarModelId = 3,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 31,
                            CarModelId = 3,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 32,
                            CarModelId = 3,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 33,
                            CarModelId = 4,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 34,
                            CarModelId = 4,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 35,
                            CarModelId = 4,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 36,
                            CarModelId = 4,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 37,
                            CarModelId = 4,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 38,
                            CarModelId = 4,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 39,
                            CarModelId = 5,
                            DaysInService = 0
                        },
                        new
                        {
                            Id = 40,
                            CarModelId = 5,
                            DaysInService = 0
                        });
                });

            modelBuilder.Entity("TeslaRent_01.WebApplication.Server.Data.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Acceleration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DailyRateLongTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyRateMidTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyRateShortTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaxRange")
                        .HasColumnType("int");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acceleration = 3.1m,
                            BodyType = "Sedan",
                            DailyRateLongTerm = 165m,
                            DailyRateMidTerm = 200m,
                            DailyRateShortTerm = 220m,
                            Description = "A compact electric sedan offering high performance and range.",
                            MaxRange = 491,
                            MaxSpeed = 261,
                            Name = "Tesla Model 3",
                            Seats = 5
                        },
                        new
                        {
                            Id = 2,
                            Acceleration = 5.0m,
                            BodyType = "SUV",
                            DailyRateLongTerm = 270m,
                            DailyRateMidTerm = 315m,
                            DailyRateShortTerm = 350m,
                            Description = "A spacious electric SUV with advanced features and great range.",
                            MaxRange = 499,
                            MaxSpeed = 217,
                            Name = "Tesla Model Y",
                            Seats = 5
                        },
                        new
                        {
                            Id = 3,
                            Acceleration = 2.1m,
                            BodyType = "Sedan",
                            DailyRateLongTerm = 375m,
                            DailyRateMidTerm = 450m,
                            DailyRateShortTerm = 500m,
                            Description = "A luxury electric sedan with impressive range and acceleration.",
                            MaxRange = 652,
                            MaxSpeed = 322,
                            Name = "Tesla Model S",
                            Seats = 5
                        },
                        new
                        {
                            Id = 4,
                            Acceleration = 2.6m,
                            BodyType = "SUV",
                            DailyRateLongTerm = 500m,
                            DailyRateMidTerm = 600m,
                            DailyRateShortTerm = 650m,
                            Description = "A premium electric SUV with falcon-wing doors and roomy interior.",
                            MaxRange = 543,
                            MaxSpeed = 262,
                            Name = "Tesla Model X",
                            Seats = 7
                        },
                        new
                        {
                            Id = 5,
                            Acceleration = 3.0m,
                            BodyType = "Pickup",
                            DailyRateLongTerm = 525m,
                            DailyRateMidTerm = 640m,
                            DailyRateShortTerm = 700m,
                            Description = "A futuristic electric pickup truck built for durability and power.",
                            MaxRange = 750,
                            MaxSpeed = 210,
                            Name = "Tesla Cybertruck",
                            Seats = 6
                        });
                });

            modelBuilder.Entity("TeslaRent_01.WebApplication.Server.Data.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Palma",
                            Country = "Spain",
                            Name = "Palma Airport",
                            Street = "Carrer del Camp Franc",
                            StreetNumber = "2",
                            ZipCode = "07199"
                        },
                        new
                        {
                            Id = 2,
                            City = "Palma",
                            Country = "Spain",
                            Name = "Palma City Center",
                            Street = "Carrer del 31 de Desembre",
                            StreetNumber = "3",
                            ZipCode = "07003"
                        },
                        new
                        {
                            Id = 3,
                            City = "Alcudia",
                            Country = "Spain",
                            Name = "Alcudia",
                            Street = "Av. Pere Mas i Reus",
                            StreetNumber = "36A",
                            ZipCode = "07410"
                        },
                        new
                        {
                            Id = 4,
                            City = "Manacor",
                            Country = "Spain",
                            Name = "Manacor",
                            Street = "Carrer del Pintor Joan Gris",
                            StreetNumber = "13",
                            ZipCode = "07500"
                        });
                });

            modelBuilder.Entity("TeslaRent_01.WebApplication.Server.Data.Reservation", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndLocationId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("EndLocationId");

                    b.HasIndex("StartLocationId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarId = 4,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 3,
                            CarId = 7,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 4,
                            CarId = 10,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 5,
                            CarId = 13,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 6,
                            CarId = 16,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 7,
                            CarId = 17,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 8,
                            CarId = 19,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 9,
                            CarId = 21,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 10,
                            CarId = 23,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 11,
                            CarId = 25,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 12,
                            CarId = 27,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 13,
                            CarId = 29,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 14,
                            CarId = 32,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 15,
                            CarId = 33,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 16,
                            CarId = 37,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 17,
                            CarId = 38,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 18,
                            CarId = 39,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 1,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 1
                        },
                        new
                        {
                            Id = 19,
                            CarId = 2,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 20,
                            CarId = 5,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 21,
                            CarId = 8,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 22,
                            CarId = 11,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 23,
                            CarId = 14,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 24,
                            CarId = 18,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 25,
                            CarId = 20,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 26,
                            CarId = 22,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 27,
                            CarId = 28,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 28,
                            CarId = 30,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 29,
                            CarId = 34,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 30,
                            CarId = 36,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 31,
                            CarId = 40,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 2,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 2
                        },
                        new
                        {
                            Id = 32,
                            CarId = 3,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 3,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 3
                        },
                        new
                        {
                            Id = 33,
                            CarId = 6,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 3,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 3
                        },
                        new
                        {
                            Id = 34,
                            CarId = 9,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 3,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 3
                        },
                        new
                        {
                            Id = 35,
                            CarId = 24,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 3,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 3
                        },
                        new
                        {
                            Id = 36,
                            CarId = 12,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 3,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 3
                        },
                        new
                        {
                            Id = 37,
                            CarId = 15,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 4,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 4
                        },
                        new
                        {
                            Id = 38,
                            CarId = 26,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 4,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 4
                        },
                        new
                        {
                            Id = 39,
                            CarId = 31,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 4,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 4
                        },
                        new
                        {
                            Id = 40,
                            CarId = 35,
                            Email = "Tesla@Rent.com",
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            EndLocationId = 4,
                            FirstName = "Tesla",
                            LastName = "Rent",
                            PhoneNumber = "+48123456789",
                            Price = 0.0m,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            StartLocationId = 4
                        });
                });

            modelBuilder.Entity("TeslaRent_01.WebApplication.Server.Models.CarModelVM", b =>
                {
                    b.Property<int>("CarModelId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CarModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.ToTable("AvailableCarModelVMs");
                });

            modelBuilder.Entity("TeslaRent_01.WebApplication.Server.Models.CarVM", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.ToTable("AvailableCarVMs");
                });

            modelBuilder.Entity("TeslaRent_01.WebApplication.Server.Data.Car", b =>
                {
                    b.HasOne("TeslaRent_01.WebApplication.Server.Data.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("TeslaRent_01.WebApplication.Server.Data.Reservation", b =>
                {
                    b.HasOne("TeslaRent_01.WebApplication.Server.Data.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeslaRent_01.WebApplication.Server.Data.Location", "EndLocation")
                        .WithMany()
                        .HasForeignKey("EndLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeslaRent_01.WebApplication.Server.Data.Location", "StartLocation")
                        .WithMany()
                        .HasForeignKey("StartLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("EndLocation");

                    b.Navigation("StartLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
